/**
 * Standardized Application Error Codes
 */
export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_URL: 'INVALID_URL',
  UNSUPPORTED_PLATFORM: 'UNSUPPORTED_PLATFORM',
  PRIVATE_MEDIA_RESTRICTED: 'PRIVATE_MEDIA_RESTRICTED',
  DRM_PROTECTED: 'DRM_PROTECTED',
  EXTRACTION_FAILED: 'EXTRACTION_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  FILE_SIZE_LIMIT_EXCEEDED: 'FILE_SIZE_LIMIT_EXCEEDED',
  STREAM_PIPELINE_ERROR: 'STREAM_PIPELINE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
});
